invitees = ["Adam", "James", "Jane"]
print(f"Dear {invitees[0].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[1].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[2].title()}, I would like to invite you to the dinner.")
print(f"{invitees[2].title()} cannot make it to the dinner.")
invitees[2] = "Joshua"
print(f"Dear {invitees[0].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[1].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[2].title()}, I would like to invite you to the dinner.")
print("We have found a bigger table, so I will invite new people")
invitees.insert(0, "Diana")
invitees.insert(3, "Ryan")
invitees.append("John")
print(f"Dear {invitees[0].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[1].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[2].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[3].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[4].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[5].title()}, I would like to invite you to the dinner.")
print("Only two more people can be invited")
popped_invitee = invitees.pop()
print(f"Dear {popped_invitee}, I am sorry but we are full and I cannot not invite you anymore.")
popped_invitee = invitees.pop()
print(f"Dear {popped_invitee}, I am sorry but we are full and I cannot not invite you anymore.")
popped_invitee = invitees.pop()
print(f"Dear {popped_invitee}, I am sorry but we are full and I cannot not invite you anymore.")
popped_invitee = invitees.pop()
print(f"Dear {popped_invitee}, I am sorry but we are full and I cannot not invite you anymore.")
print(f"Dear {invitees[0].title()}, I would like to invite you to the dinner.")
print(f"Dear {invitees[1].title()}, I would like to invite you to the dinner.")
del invitees[0]
del invitees[0]
print(invitees)
